import os
import json

herbs = {
    "Abies_pindrow": 0, "Abies_webbiana": 1, "Abrus_precatorius": 2, "Acalypha_ciliata": 3,
    "Acalypha_fruticosa": 4, "Acalypha_indica": 5, "Acanthospermum_hispidum": 6, "Acanthus_ilicifolius": 7,
    "Achillea_millefolium": 8, "Aconitum_ferox": 9, "Aconitum_napellus": 10, "Aconitum_spicatum": 11,
    "Aconitum_violaceum": 12, "Acorus_calamus": 13, "Actaea_spicata": 14, "Adhatoda_vasica": 15,
    "Adina_cordifolia": 16, "Aegle_marmelos": 17, "Aframomum_melegueta": 18, "Agrimonia_eupatoria": 19,
    "Agropyron_repens": 20, "Ailanthus_excelsa": 21, "Ainsliaea_aptera": 22, "Aleurites_moluccana": 23,
    "Alhagi_pseudalhagi": 24, "Allium_cepa": 25, "Allium_sativum": 26, "Aloe_vera": 27,
    "Alpinia_galanga": 28, "Alpinia_malaccensis": 29, "Alpinia_officinarum": 30, "Alpinia_speciosa": 31,
    "Amomum_aromaticum": 32, "Amomum_subulatum": 33, "Amygdalus_communis": 34, "Amygdalus_persica": 35,
    "Anacyclus_pyrethrum": 36, "Anaphalis_neelgerriana": 37, "Andrographis_echioides": 38,
    "Andrographis_paniculata": 39, "Anemone_obtusiloba": 40, "Anethum_graveolens": 41,
    "Anthocephalus_cadamba": 42, "Arachis_hypogaea": 43, "Arctium_lappa": 44,
    "Artemisia_absinthium": 45, "Artemisia_maritima": 46, "Artemisia_vestita": 47,
    "Artemisia_vulgaris": 48, "Arundo_donax": 49, "Asclepias_curassavica": 50,
    "Asparagus_racemosus": 51, "Asteracantha_longifolia": 52, "Atropa_acuminata": 53,
    "Atylosia_goensis": 54, "Avena_sativa": 55, "Avicennia_officinalis": 56, "Azadirachta_indica": 57,
    "Bacopa_monnieri": 58, "Baliospermum_montanum": 59, "Bambusa_bambos": 60, "Barleria_buxifolia": 61,
    "Barleria_cristata": 62, "Barleria_prionitis": 63, "Barleria_strigosa": 64, "Berberis_aristata": 65,
    "Bidens_pilosa": 66, "Blepharis_edulis": 67, "Blepharis_linariifolia": 68, "Blumea_balsamifera": 69,
    "Blumea_densiflora": 70, "Blumea_eriantha": 71, "Blumea_lacera": 72, "Boerhavia_diffusa": 73,
    "Boswellia_serrata": 74, "Brassica_juncea": 75, "Breynia_retusa": 76, "Bridelia_montana": 77,
    "Brugmansia_suaveolens": 78, "Butea_monosperma": 79, "Butea_superba": 80, "Cajanus_cajan": 81,
    "Calendula_officinalis": 82, "Callicarpa_macrophylla": 83, "Calotropis_gigantea": 84,
    "Calotropis_procera": 85, "Caltha_palustris": 86, "Canthium_parviflorum": 87,
    "Capsicum_annuum": 88, "Capsicum_frutescens": 89, "Carum_carvi": 90, "Cassia_fistula": 91,
    "Cedrus_deodara": 92, "Celastrus_paniculatus": 93, "Centaurea_behen": 94, "Centella_asiatica": 95,
    "Ceropegia_bulbosa": 96, "Ceropegia_juncea": 97, "Chrozophora_plicata": 98,
    "Chrysanthemum_indicum": 99, "Cicer_arietinum": 100, "Cichorium_endivia": 101,
    "Cichorium_intybus": 102, "Cimicifuga_racemosa": 103, "Cinchona_officinalis": 104,
    "Cinnamomum_verum": 105, "Cissus_quadrangularis": 106, "Clematis_gouriana": 107,
    "Clerodendrum_aculeatum": 108, "Clerodendrum_indicum": 109, "Clerodendrum_inerme": 110,
    "Clerodendrum_phlomidis": 111, "Clerodendrum_serratum": 112, "Clitoria_ternatea": 113,
    "Coffea_arabica": 114, "Coix_lacryma-jobi": 115, "Commiphora_mukul": 116,
    "Convolvulus_pluricaulis": 117, "Cordia_dichotoma": 118, "Coriandrum_sativum": 119,
    "Costus_speciosus": 120, "Crataegus_oxyacantha": 121, "Crotalaria_juncea": 122,
    "Crotalaria_verrucosa": 123, "Croton_tiglium": 124, "Cryptolepis_buchanani": 125,
    "Cuminum_cyminum": 126, "Curcuma_amada": 127, "Curcuma_angustifolia": 128,
    "Curcuma_aromatica": 129, "Curcuma_caesia": 130, "Curcuma_longa": 131, "Curcuma_zedoaria": 132,
    "Cydonia_oblonga": 133, "Cymbopogon_citratus": 134, "Cymbopogon_flexuosus": 135,
    "Cynara_scolymus": 136, "Cynodon_dactylon": 137, "Cytisus_scoparius": 138,
    "Dactyloctenium_aegyptium": 139, "Dalbergia_lanceolaria": 140, "Dalbergia_latifolia": 141,
    "Dalbergia_sissoo": 142, "Dalbergia_volubilis": 143, "Datura_alba": 144, "Datura_innoxia": 145,
    "Datura_metel": 146, "Datura_stramonium": 147, "Decalepis_hamiltonii": 148,
    "Delphinium_ajacis": 149, "Delphinium_brunonianum": 150, "Delphinium_consolida": 151,
    "Delphinium_denudatum": 152, "Delphinium_elatum": 153, "Delphinium_vestitum": 154,
    "Delphinium_zalil": 155, "Desmodium_gangeticum": 156, "Desmostachya_bipinnata": 157,
    "Dicoma_tomentosa": 158, "Dolichos_biflorus": 159, "Dolichos_falcatus": 160,
    "Dolichos_lablab": 161, "Doronicum_hookeri": 162, "Doronicum_pardalianches": 163,
    "Doronicum_roylei": 164, "Dregea_volubilis": 165, "Drypetes_roxburghii": 166,
    "Duranta_plumieri": 167, "Ecbolium_linneanum": 168, "Echinochloa_colona": 169,
    "Echinochloa_crus-galli": 170, "Echinops_echinatus": 171, "Eclipta_alba": 172,
    "Eclipta_prostrata": 173, "Elephantopus_scaber": 174, "Elettaria_cardamomum": 175,
    "Eleusine_coracana": 176, "Eleusine_indica": 177, "Elytraria_crenata": 178,
    "Emblica_officinalis": 179, "Emilia_sonchifolia": 180, "Erigeron_canadensis": 181,
    "Eriobotrya_japonica": 182, "Erythrina_indica": 183, "Erythrina_stricta": 184,
    "Eulaliopsis_binata": 185, "Eupatorium_odoratum": 186, "Eupatorium_triplinerve": 187,
    "Euphorbia_antiquorum": 188, "Ferula_asafoetida": 189, "Foeniculum_vulgare": 190,
    "Fumaria_indica": 191, "Glycyrrhiza_glabra": 192, "Gymnema_sylvestre": 193,
    "Hedychium_spicatum": 194, "Hemidesmus_indicus": 195, "Holarrhena_antidysenterica": 196,
    "Inula_racemosa": 197, "Ipomoea_batatas": 198, "Justicia_adhatoda": 199,
    "Lavandula_angustifolia": 200, "Lawsonia_inermis": 201, "Matricaria_chamomilla": 202,
    "Mentha_spicata": 203, "Moringa_oleifera": 204, "Murraya_koenigii": 205,
    "Myristica_fragrans": 206, "Nardostachys_jatamansi": 207, "Nelumbo_nucifera": 208,
    "Nigella_sativa": 209, "Ocimum_basilicum": 210, "Ocimum_tenuiflorum": 211,
    "Operculina_turpethum": 212, "Origanum_vulgare": 213, "Pandanus_amaryllifolius": 214,
    "Phyllanthus_niruri": 215, "Picrorhiza_kurroa": 216, "Pimpinella_anisum": 217,
    "Piper_longum": 218, "Piper_nigrum": 219, "Plectranthus_amboinicus": 220,
    "Plumbago_zeylanica": 221, "Psoralea_corylifolia": 222, "Pterocarpus_santalinus": 223,
    "Rauvolfia_serpentina": 224, "Rosmarinus_officinalis": 225, "Rubia_cordifolia": 226,
    "Salvia_officinalis": 227, "Santalum_album": 228, "Saussurea_costus": 229,
    "Sida_cordifolia": 230, "Swertia_chirata": 231, "Syzygium_aromaticum": 232,
    "Tephrosia_purpurea": 233, "Terminalia_arjuna": 234, "Terminalia_bellirica": 235,
    "Terminalia_chebula": 236, "Thymus_vulgaris": 237, "Tinospora_cordifolia": 238,
    "Tinospora_sinensis": 239, "Trachyspermum_ammi": 240, "Tribulus_terrestris": 241,
    "Trigonella_foenum-graecum": 242, "Uraria_picta": 243, "Valeriana_wallichii": 244,
    "Vetiveria_zizanioides": 245, "Vitex_negundo": 246, "Withania_somnifera": 247,
    "Zanthoxylum_armatum": 248, "Zingiber_officinale": 249,
    "Euphorbia_hirta": 250, "Euphorbia_hypericifolia": 251, "Euphorbia_neriifolia": 252,
    "Euphorbia_nivulia": 253, "Euphorbia_pilosa": 254, "Euphorbia_resinifera": 255,
    "Euphorbia_royleana": 256, "Euphorbia_thymifolia": 257, "Euphorbia_tirucalli": 258,
    "Excoecaria_agallocha": 259, "Galium_aparine": 260, "Galium_verum": 261,
    "Gardenia_gummifera": 262, "Gardenia_jasminoides": 263, "Gardenia_latifolia": 264,
    "Gardenia_resinifera": 265, "Gardenia_turgida": 266, "Geophila_repens": 267,
    "Geum_urbanum": 268, "Glossocardia_bosvallea": 269, "Glycine_max": 270,
    "Gmelina_arborea": 271, "Gmelina_asiatica": 272, "Grangea_maderaspatana": 273,
    "Graptophyllum_pictum": 274, "Guettarda_speciosa": 275, "Guizotia_abyssinica": 276,
    "Gymnema_hirsutum": 277, "Gymnema_montanum": 278, "Haplanthus_verticillatus": 279,
    "Hedychium_coronarium": 280, "Hedyotis_corymbosa": 281, "Helianthus_annuus": 282,
    "Helleborus_niger": 283, "Homonoia_riparia": 284, "Hordeum_vulgare": 285,
    "Hura_crepitans": 286, "Hygrophila_auriculata": 287, "Hymenodictyon_excelsum": 288,
    "Hyoscyamus_muticus": 289, "Hyoscyamus_niger": 290, "Imperata_cylindrica": 291,
    "Ixora_coccinea": 292, "Ixora_javanica": 293, "Ixora_pavetta": 294,
    "Jatropha_curcas": 295, "Jatropha_glandulifera": 296, "Jatropha_gossypiifolia": 297,
    "Jatropha_multifida": 298, "Juniperus_communis": 299, "Juniperus_virginiana": 300,
    "Justicia_betonica": 301, "Justicia_gendarussa": 302, "Justicia_procumbens": 303,
    "Kaempferia_galanga": 304, "Kaempferia_rotunda": 305, "Lactuca_sativa": 306,
    "Lactuca_serriola": 307, "Lactuca_virosa": 308, "Lantana_camara": 309,
    "Larix_griffithiana": 310, "Lathyrus_sativus": 311, "Launaea_mucronata": 312,
    "Launaea_pinnatifida": 313, "Lavandula_stoechas": 314, "Lens_culinaris": 315,
    "Lepidagathis_cristata": 316, "Lepidagathis_trinervis": 317, "Ligularia_tussilaginea": 318,
    "Lippia_geminata": 319, "Lolium_temulentum": 320, "Lycium_barbarum": 321,
    "Lycopersicon_esculentum": 322, "Mallotus_philippensis": 323, "Malus_pumila": 324,
    "Mandragora_officinarum": 325, "Manihot_esculenta": 326, "Medicago_sativa": 327,
    "Meyna_laxiflora": 328, "Mitragyna_parvifolia": 329, "Morinda_citrifolia": 330,
    "Mucuna_monosperma": 331, "Mucuna_prurita": 332, "Mussaenda_frondosa": 333,
    "Naravelia_zeylanica": 334, "Neuracanthus_sphaerostachyus": 335, "Nicotiana_tabacum": 336,
    "Nigella_damascena": 337, "Nilgirianthus_ciliatus": 338, "Oldenlandia_umbellata": 339,
    "Ophiorrhiza_mungos": 340, "Oryza_sativa": 341, "Ougeinia_dalbergioides": 342,
    "Paederia_foetida": 343, "Parthenium_hysterophorus": 344, "Paspalum_distichum": 345,
    "Pavetta_indica": 346, "Pedilanthus_tithymaloides": 347, "Perilepta_auriculata": 348,
    "Peristrophe_bicalyculata": 349, "Phaseolus_aconitifolius": 350, "Phaseolus_adenanthus": 351,
    "Phaseolus_mungo": 352, "Phaseolus_radiatus": 353, "Phaseolus_trilobus": 354,
    "Phlogacanthus_thyrsiflorus": 355, "Phragmites_communis": 356, "Phragmites_karka": 357,
    "Phyla_nodiflora": 358, "Phyllanthus_amarus": 359, "Phyllanthus_distichus": 360,
    "Phyllanthus_fraternus": 361, "Phyllanthus_simplex": 362, "Phyllanthus_urinaria": 363,
    "Physalis_alkekengi": 364, "Physalis_angulata": 365, "Physalis_minima": 366,
    "Physalis_peruviana": 367, "Physochlaina_praealta": 368, "Picea_smithiana": 369,
    "Pinus_excelsa": 370, "Pinus_gerardiana": 371, "Pinus_kesiya": 372, "Pinus_roxburghii": 373,
    "Piscidia_piscipula": 374, "Pluchea_indica": 375, "Pongamia_pinnata": 376,
    "Potentilla_anserina": 377, "Potentilla_arbuscula": 378, "Potentilla_nepalensis": 379,
    "Premna_latifolia": 380, "Premna_tomentosa": 381, "Prunus_amygdalus": 382,
    "Prunus_armeniaca": 383, "Prunus_avium": 384, "Prunus_cerasoides": 385,
    "Prunus_cerasus": 386, "Prunus_domestica": 387, "Prunus_mahaleb": 388, "Prunus_persica": 389,
    "Pseudarthria_viscida": 390, "Pterocarpus_marsupium": 391, "Pueraria_lobata": 392,
    "Pueraria_tuberosa": 393, "Putranjiva_roxburghii": 394, "Pyrus_communis": 395,
    "Quillaja_saponaria": 396, "Randia_dumetorum": 397, "Randia_uliginosa": 398,
    "Ranunculus_arvensis": 399, "Ranunculus_muricatus": 400, "Ranunculus_sceleratus": 401,
    "Rhinacanthus_nasutus": 402, "Rhynchosia_minima": 403, "Ricinus_communis": 404,
    "Rosa_alba": 405, "Rosa_centifolia": 406, "Rosa_chinensis": 407, "Rosa_damascena": 408,
    "Rosa_macrophylla": 409, "Rosa_moschata": 410, "Rosa_multiflora": 411, "Rosa_rubra": 412,
    "Rosa_sericea": 413, "Rosa_webbiana": 414, "Rubia_tinctorum": 415, "Rubus_ellipticus": 416,
    "Ruellia_strepens": 417, "Ruellia_tuberosa": 418, "Rungia_pectinata": 419,
    "Rungia_repens": 420, "Saccharum_officinarum": 421, "Saccharum_spontaneum": 422,
    "Santolina_chamaecyparissus": 423, "Sapium_sebiferum": 424, "Sauropus_androgynus": 425,
    "Saussurea_hypoleuca": 426, "Saussurea_lappa": 427, "Saussurea_obvallata": 428,
    "Securinega_leucopyrus": 429, "Senecio_vulgaris": 430, "Sesbania_bispinosa": 431,
    "Sesbania_grandiflora": 432, "Sesbania_sesban": 433, "Setaria_italica": 434,
    "Sibbaldia_parviflora": 435, "Siegesbeckia_orientalis": 436, "Silybum_marianum": 437,
    "Solanum_dulcamara": 438, "Solanum_elaeagnifolium": 439, "Solanum_erianthum": 440,
    "Solanum_ferox": 441, "Solanum_indicum": 442, "Solanum_melongena": 443,
    "Solanum_nigrum": 444, "Solanum_spirale": 445, "Solanum_torvum": 446,
    "Solanum_trilobatum": 447, "Solanum_tuberosum": 448, "Solanum_xanthocarpum": 449,
    "Sonchus_arvensis": 450, "Sonchus_asper": 451, "Sonchus_oleraceus": 452,
    "Sophora_japonica": 453, "Sophora_mollis": 454, "Sorghum_vulgare": 455,
    "Spermacoce_hispida": 456, "Sphaeranthus_indicus": 457, "Stachytarpheta_jamaicensis": 458,
    "Strobilanthes_callosus": 459, "Sutherlandia_frutescens": 460, "Tagetes_erecta": 461,
    "Tanacetum_vulgare": 462, "Taraxacum_officinale": 463, "Tarenna_asiatica": 464,
    "Taverniera_cuneifolia": 465, "Tectona_grandis": 466, "Teramnus_labialis": 467,
    "Themeda_arundinacea": 468, "Tragia_involucrata": 469, "Tragopogon_porrifolius": 470,
    "Trewia_nudiflora": 471, "Tricholepis_glaberrima": 472, "Trifolium_pratense": 473,
    "Trigonella_corniculata": 474, "Triticum_aestivum": 475, "Tussilago_farfara": 476,
    "Uncaria_gambier": 477, "Uraria_alopecuroides": 478, "Uraria_crinita": 479,
    "Verbena_officinalis": 480, "Vernonia_cinerea": 481, "Vernonia_patula": 482,
    "Vicia_faba": 483, "Vicoa_indica": 484, "Vitex_agnus_castus": 485,
    "Vitex_leucoxylon": 486, "Vitex_peduncularis": 487, "Vitex_trifolia": 488,
    "Wedelia_biflora": 489, "Wendlandia_tinctoria": 490, "Withania_ashwagandha": 491,
    "Withania_coagulans": 492, "Xanthium_strumarium": 493, "Zea_mays": 494,
    "Zingiber_cassumunar": 495, "Zingiber_zerumbet": 496, "Zornia_diphylla": 497,
    "Geranium_wallichianum": 498, "Nerium_oleander": 499, "Ocimum_sanctum": 500,
    "Lobelia_chinensis": 501, "Narcissus_tazetta": 502, "Moringa_pterygosperma": 503,
    "Dillenia_indica": 504, "Alangium_lamarckii": 505, "Hibiscus_rosa_sinensis": 506,
    "Lobelia_inflata": 507, "Curculigo_orchioides": 508, "Crossandra_infundibuliformis": 509,
    "Coleus_amboinicus": 510, "Passiflora_incarnata": 511, "Crinum_latifolium": 512,
    "Mentha_piperata": 513, "Polianthes_tuberosa": 514, "Aconitum_heterophyllum": 515,
    "Crinum_asiaticum": 516
}

out_dir = os.path.join(os.path.dirname(__file__), "newMeta")
os.makedirs(out_dir, exist_ok=True)

for herb, idx in herbs.items():
    common_name = herb.replace("_", " ")
    data = {
        "id": idx,
        "scientific_name": herb.replace("_", " "),
        "common_name": common_name,
        "family": "",
        "description": "",
        "medicinal_uses": [],
        "parts_used": [],
        "habitat": "",
        "distribution": [],
        "ayurvedic_name": "",
        "active_compounds": [],
        "warnings": ""
    }
    with open(os.path.join(out_dir, f"{herb}.json"), "w") as f:
        json.dump(data, f, indent=2)

print(f"Created {len(herbs)} JSON files in newMeta/")
